package Units;

public enum UnitType {
	ARCHER_RABBIT, ARCHER_MOUSE, ARCHER_RAT, ARCHER_SQUIRREL,
	FOOTMAN_RABBIT, FOOTMAN_MOUSE, FOOTMAN_RAT, FOOTMAN_SQUIRREL,
	KNIGHT_RABBIT, KNIGHT_MOUSE, KNIGHT_RAT, KNIGHT_SQUIRREL
}
